// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKXJ1bsd2W19__QDUcwiXZVZ1EanlXrDg',
    appId: '1:875017917221:web:96d60dd960dafa1f3dc0cc',
    messagingSenderId: '875017917221',
    projectId: 'food-delivery-43e52',
    authDomain: 'food-delivery-43e52.firebaseapp.com',
    storageBucket: 'food-delivery-43e52.appspot.com',
    measurementId: 'G-ZRRLC4WKSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFNVJS-NHb81O-1jAnCv6Bezk0zWIt3yY',
    appId: '1:875017917221:android:0c9c44c4fc81cd103dc0cc',
    messagingSenderId: '875017917221',
    projectId: 'food-delivery-43e52',
    storageBucket: 'food-delivery-43e52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pLd0bKzpHF9l1PgOgx13bO36WtK6jfw',
    appId: '1:875017917221:ios:8b67d88f0b78ca2f3dc0cc',
    messagingSenderId: '875017917221',
    projectId: 'food-delivery-43e52',
    storageBucket: 'food-delivery-43e52.appspot.com',
    androidClientId: '875017917221-j6smg6tp7cv7vuvulf5a25j86fmabdip.apps.googleusercontent.com',
    iosClientId: '875017917221-h6foc8gagm1ou56uk59sie9epi3d1tct.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pLd0bKzpHF9l1PgOgx13bO36WtK6jfw',
    appId: '1:875017917221:ios:62444c82865ea2b93dc0cc',
    messagingSenderId: '875017917221',
    projectId: 'food-delivery-43e52',
    storageBucket: 'food-delivery-43e52.appspot.com',
    androidClientId: '875017917221-j6smg6tp7cv7vuvulf5a25j86fmabdip.apps.googleusercontent.com',
    iosClientId: '875017917221-fe2j9d4bj45u6drro2b38fl0mehm353m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
